{
    'name': 'Zakheni Tender Management',
    'summary': 'Track and manage tenders you are bidding on',
    'version': '18.0.1.5.0',
    'category': 'Services/Project',
    'license': 'LGPL-3',
    'author': 'Zakheni ICT (Pty) Ltd',
    'website': 'https://www.zakhenict.co.za',
    'depends': [
        'mail',
        'portal',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/stages.xml',
        'data/cron_data.xml',
        'views/tender_stage_views.xml',
        'views/tender_views.xml',
        'views/tender_category_views.xml',
        'views/tender_bid_no_bid_views.xml',
        'views/tender_compliance_views.xml',
        'views/tender_ai_analysis_views.xml',
        'views/dashboard_views.xml',
        'views/analysis_views.xml',
        'views/portal_templates.xml',
        'views/tender_service_category_views.xml',
        'views/tender_company_profile_views.xml',
        'views/tender_feed_views.xml',
        'views/tender_feed_match_views.xml',
        'views/tender_feed_keyword_search_views.xml',
        'views/tender_feed_keyword_config_views.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'zakheni_tender/static/src/scss/tender_dashboard.scss',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
