from . import crm_lead
from . import crm_lead_score
from . import crm_scoring_rule
from . import crm_lead_grade
from . import crm_pipeline_automation
from . import crm_competitor
from . import crm_territory
from . import crm_sla
from . import crm_email_sequence
from . import crm_forecast
from . import res_config_settings
from . import crm_target
