{
    'name': 'Zakheni Accounting - Enterprise Features',
    'summary': 'Accounting dashboard, dunning/follow-up, cash flow forecast, deferred revenue, consolidation',
    'version': '18.0.1.0.0',
    'category': 'Accounting',
    'license': 'LGPL-3',
    'author': 'Zakheni ICT (Pty) Ltd',
    'website': 'https://www.zakhenict.co.za',
    'depends': [
        'account',
        'account_due_list',
        'account_fiscal_year',
        'account_lock_to_date',
        'account_journal_lock_date',
        'account_dashboard_banner',
        'account_spread_cost_revenue',
        'account_reconcile_oca',
        'account_reconcile_model_oca',
        'account_move_template',
        'account_maturity_date_default',
        'partner_aging',
        'account_statement_import_online',
        'account_statement_import_file',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/followup_data.xml',
        'data/cron_data.xml',
        'views/account_cash_forecast_views.xml',
        'views/account_followup_views.xml',
        'views/account_consolidation_views.xml',
        'views/account_dashboard_views.xml',
        'wizards/account_statement_wizard.xml',
        'views/res_partner_views.xml',
        'views/res_config_settings_views.xml',
        'views/menus.xml',
        'report/report_dunning_letter.xml',
        'report/customer_statement.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
