from . import asset_category
from . import asset_location
from . import asset_asset
from . import asset_assignment
from . import asset_maintenance
from . import asset_depreciation
from . import asset_dashboard
from . import res_config_settings
from . import asset_qr
from . import asset_audit
from . import asset_bulk_update_wizard
