{
    'name': 'Zakheni CRM — Enterprise Features',
    'summary': 'Advanced lead scoring, pipeline automation, territory management, forecasting, SLA tracking, and win/loss analysis.',
    'version': '18.0.1.0.0',
    'category': 'Sales/CRM',
    'license': 'LGPL-3',
    'author': 'Zakheni ICT (Pty) Ltd',
    'website': 'https://www.zakhenict.co.za',
    'depends': [
        'crm',
        'sales_team',
        'mail',
        'base_setup',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/zakheni_crm_security.xml',
        'data/crm_lead_grade_data.xml',
        'data/crm_scoring_rule_data.xml',
        'data/crm_sla_data.xml',
        'data/crm_email_sequence_data.xml',
        'data/ir_cron_data.xml',
        'views/crm_lead_views.xml',
        'views/crm_lead_score_views.xml',
        'views/crm_scoring_rule_views.xml',
        'views/crm_lead_grade_views.xml',
        'views/crm_pipeline_automation_views.xml',
        'views/crm_competitor_views.xml',
        'views/crm_territory_views.xml',
        'views/crm_sla_views.xml',
        'views/crm_email_sequence_views.xml',
        'views/crm_forecast_views.xml',
        'views/res_config_settings_views.xml',
        'views/crm_target_views.xml',
        'views/zakheni_crm_menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
