{
    'name': 'Zakheni Email Marketing — Enterprise Features',
    'summary': 'Advanced email marketing with drip campaigns, automation, A/B testing, segmentation, landing pages, lead scoring, and ROI analytics.',
    'version': '18.0.1.0.0',
    'category': 'Marketing/Email Marketing',
    'license': 'LGPL-3',
    'author': 'Zakheni ICT (Pty) Ltd',
    'website': 'https://www.zakhenict.co.za',
    'depends': [
        'mass_mailing',
        'mass_mailing_crm',
        'crm',
        'mail',
        'utm',
        'link_tracker',
        'contacts',
        'sale',
        'sale_crm',
        'web_editor',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/marketing_security.xml',
        'data/marketing_cron_data.xml',
        'data/marketing_sequence_data.xml',
        'data/marketing_demo_data.xml',
        'views/marketing_campaign_views.xml',
        'views/marketing_campaign_step_views.xml',
        'views/marketing_automation_views.xml',
        'views/marketing_automation_action_views.xml',
        'views/marketing_segment_views.xml',
        'views/marketing_lead_score_views.xml',
        'views/marketing_calendar_views.xml',
        'views/marketing_landing_page_views.xml',
        'views/marketing_subscription_preference_views.xml',
        'views/marketing_reengagement_views.xml',
        'views/marketing_roi_views.xml',
        'views/mailing_mailing_views.xml',
        'views/mailing_list_views.xml',
        'views/mailing_contact_views.xml',
        'views/marketing_menus.xml',
        'views/res_config_settings_views.xml',
        'views/marketing_dashboard_views.xml',
        'wizards/marketing_campaign_report_wizard_views.xml',
        'report/marketing_report_views.xml',
    ],
    'demo': [
        'demo/marketing_demo_campaign.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'assets': {
        'web.assets_backend': [
            'zakheni_email_marketing/static/src/scss/marketing_dashboard.scss',
            'zakheni_email_marketing/static/src/js/marketing_calendar.js',
            'zakheni_email_marketing/static/src/js/marketing_dashboard.js',
        ],
    },
}
